#!/usr/bin/env php
<?php

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Debug\Debug;

umask(0000);

set_time_limit(0);
error_reporting(E_ALL);
ini_set('display_errors', 1);

/** @var Composer\Autoload\ClassLoader $loader */
$loader = require __DIR__.'/app/autoload.php';

$input = new ArgvInput();
$env = $input->getParameterOption(['--env', '-e'], getenv('SYMFONY_ENV') ?: 'dev');
$debug = getenv('SYMFONY_DEBUG') !== '0' && !$input->hasParameterOption(['--no-debug', '']) && $env !== 'prod';

if ($debug) {
    Debug::enable();
}

$kernel = new ApiDemoKernel($env, $debug);
$application = new Application($kernel);
$application->run($input);
