name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    name: Unitary Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        coverage:
          - none
        php-version:
          - '8.0'
        dependencies:
          - 'lowest'
          - 'highest'

    steps:
      - uses: actions/checkout@v3

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
          coverage: ${{ matrix.coverage }}

      - name: "Install lowest dependencies"
        if: ${{ matrix.dependencies == 'lowest' }}
        run: "composer update --no-interaction --no-progress --prefer-lowest"

      - name: "Install highest dependencies"
        if: ${{ matrix.dependencies == 'highest' }}
        run: "composer update --no-interaction --no-progress"

      - name: "Run tests"
        run: composer test